name: httpbulb

services:
  web:
    image: ghcr.io/niklak/httpbulb:latest
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - :4443:8080
    environment:
      - SERVER_ADDR=:8080
      - SERVER_CERT_PATH=/data/certs/server-host.pem
      - SERVER_KEY_PATH=/data/certs/server-host-key.pem
    


